name: Train model
description: Trains a RandomForest model and saves model.pkl.
inputs:
- {name: preprocessed_dir, type: String}
- {name: model_output_path, type: String}
implementation:
  container:
    image: python:3.7
    command:
    - sh
    - -ec
    - |
      program_path=$(mktemp)
      printf "%s" "$0" > "$program_path"
      python3 -u "$program_path" "$@"
    - |
      def train_model(preprocessed_dir, model_output_path):
          """
          Trains a RandomForest model and saves model.pkl.
          """
          X_train = pd.read_csv(f"{preprocessed_dir}/X_train.csv")
          y_train = pd.read_csv(f"{preprocessed_dir}/y_train.csv")

          model = RandomForestRegressor(n_estimators=100, random_state=42)
          model.fit(X_train, y_train.values.ravel())

          joblib.dump(model, model_output_path)
          print("Model saved to:", model_output_path)

      import argparse
      _parser = argparse.ArgumentParser(prog='Train model', description='Trains a RandomForest model and saves model.pkl.')
      _parser.add_argument("--preprocessed-dir", dest="preprocessed_dir", type=str, required=True, default=argparse.SUPPRESS)
      _parser.add_argument("--model-output-path", dest="model_output_path", type=str, required=True, default=argparse.SUPPRESS)
      _parsed_args = vars(_parser.parse_args())

      _outputs = train_model(**_parsed_args)
    args:
    - --preprocessed-dir
    - {inputValue: preprocessed_dir}
    - --model-output-path
    - {inputValue: model_output_path}
